import React from 'react';
import { Text, View } from 'react-native';

function ContestRules(props) {

    return(
        <View>
            <Text>
            NO PURCHASE IS NECESSARY TO ENTER OR WIN. A PURCHASE DOES NOT INCREASE THE CHANCES OF WINNING.
            {"\n\n"}
            1. Eligibility: This Campaign is open only to those who sign up at olympiatop10.com and who are 21 years of age or older as of the date of entry. The Campaign is only open to legal residents of the contiguous 48 states and is void where prohibited by law. Employees of Olympia Top 10, its affiliates, subsidiaries, advertising and promotion agencies, and suppliers, (collectively the “Employees”), and immediate family members and/or those living in the same household of Employees are not eligible to participate in the Campaign. The Campaign is subject to all applicable federal, state, and local laws and regulations. Void where prohibited.\n
            {"\n\n"}
            2. Agreement to Rules: By participating, the Contestant (“You”) agree to be fully unconditionally bound by these Rules, and You represent and warrant that You meet the eligibility requirements. In addition, You agree to accept the decisions of Olympia Top 10 as final and binding as it relates to the content of this Campaign.
            {"\n\n"}
            3. Campaign Period: Entries will be accepted online starting on March 1, 2021 and ending July 31, 2021 at 12:00 PM PST. All online entries must be received by July 31, 2021 at 12:00 PM PST.
            {"\n\n"}
            4. How to Enter: The Campaign must be entered by submitting an entry using the online form provided at olympiatop10.com. The entry must fulfill all Campaign requirements, as specified, to be eligible to win a prize. Entries that are incomplete or do not adhere to the rules or specifications may be disqualified at the sole discretion of Olympia Top 10. Optional verbiage to include: You may enter only once. You must provide the information requested. You may not enter more times than indicated by using multiple email addresses, identities, or devices in an attempt to circumvent the rules. If You use fraudulent methods or otherwise attempt to circumvent the rules, your submission may be removed from eligibility at the sole discretion of Olympia Top 10.
            {"\n\n"}
            5. Prizes: The Winner(s) of the Campaign (the “Winner”) will receive $2,500. Actual/appraised value may differ at time of prize award. The specifics of the prize shall be solely determined by Olympia Top 10. No cash or other prize substitution shall be permitted except at Olympia Top 10's discretion. The prize is nontransferable. Any and all prize-related expenses, including without limitation any and all federal, state, and/or local taxes, shall be the sole responsibility of Winner. No substitution of prize or transfer/assignment of prize to others or request for the cash equivalent by Winner is permitted. Acceptance of prize constitutes permission for Olympia Top 10 to use Winner’s name, likeness, and entry for purposes of advertising and trade without further compensation unless prohibited by law.
            {"\n\n"}
            6. Odds: The odds of winning depend on the number of eligible entries received.
            {"\n\n"}
            7. Winner Selection and Notification: Winner will be selected by a random drawing under the supervision of Olympia Top 10. Winner will be notified by e-mail within five (5) days following selection of Winner. Olympia Top 10 shall have no liability for Winner’s failure to receive notices due to spam, junk e-mail, or other security settings or for Winner’s provision of incorrect or otherwise non-functioning contact information. If Winner cannot be contacted, is ineligible, fails to claim the prize within 15 days from the time award notification was sent, or fails to timely return a completed and executed declaration and release as required, the prize may be forfeited and an alternate Winner selected. Receipt by Winner of the prize offered in this Campaign is conditioned upon compliance with any and all federal, state, and local laws and regulations. ANY VIOLATION OF THESE OFFICIAL RULES BY WINNER (AT Olympia Top 10‘S SOLE DISCRETION) WILL RESULT IN WINNER’S DISQUALIFICATION AS WINNER OF THE CAMPAIGN, AND ALL PRIVILEGES AS WINNER WILL BE IMMEDIATELY TERMINATED.
            {"\n\n"}
            8. Rights Granted by You: By entering this content (e.g., photo, video, text, etc.), You understand and agree that Olympia Top 10, anyone acting on behalf of Olympia Top 10, and Olympia Top 10’s licensees, successors, and assigns, shall have the right, where permitted by law, to print, publish, broadcast, distribute, and use in any media now known or hereafter developed, in perpetuity and throughout the World, without limitation, your entry, name, portrait, picture, voice, likeness, image, statements about the Campaign, and biographical information for news, publicity, information, trade, advertising, public relations, and promotional purposes. without any further compensation, notice, review, or consent. Optional verbiage for Contests: By entering this content, You represent and warrant that your entry is an original work of authorship, and does not violate any third party’s proprietary or intellectual property rights. If your entry infringes upon the intellectual property right of another, You will be disqualified at the sole discretion of Olympia Top 10. If the content of your entry is claimed to constitute infringement of any proprietary or intellectual proprietary rights of any third party, You shall, at your sole expense, defend or settle against such claims. You shall indemnify, defend, and hold harmless Olympia Top 10 from and against any suit, proceeding, claims, liability, loss, damage, costs or expense, which Olympia Top 10 may incur, suffer, or be required to pay arising out of such infringement or suspected infringement of any third party’s right.
            {"\n\n"}
            9. Terms & Conditions: Olympia Top 10 reserves the right, in its sole discretion, to cancel, terminate, modify or suspend the Campaign should virus, bug, non-authorized human intervention, fraud, or other cause beyond Olympia Top 10’s control corrupt or affect the administration, security, fairness, or proper conduct of the Campaign. In such case, Olympia Top 10 may select the Winner from all eligible entries received prior to and/or after (if appropriate) the action taken by Olympia Top 10. Olympia Top 10 reserves the right, in its sole discretion, to disqualify any individual who tampers or attempts to tamper with the entry process or the operation of the Campaign or website or violates these Terms & Conditions. Olympia Top 10 has the right, in its sole discretion, to maintain the integrity of the Campaign, to void votes for any reason, including, but not limited to: multiple entries from the same user from different IP addresses; multiple entries from the same computer in excess of that allowed by Campaign rules; or the use of bots, macros, scripts, or other technical means for entering. Any attempt by an entrant to deliberately damage any website or undermine the legitimate operation of the Campaign may be a violation of criminal and civil laws. Should such an attempt be made, Olympia Top 10 reserves the right to seek damages to the fullest extent permitted by law.
            {"\n\n"}
            10. Limitation of Liability: By entering, You agree to release and hold harmless Olympia Top 10 and its subsidiaries, affiliates, advertising and promotion agencies, partners, representatives, agents, successors, assigns, employees, officers, and directors from any liability, illness, injury, death, loss, litigation, claim, or damage that may occur, directly or indirectly, whether caused by negligence or not, from: (i) such entrant’s participation in the Campaign and/or his/her acceptance, possession, use, or misuse of any prize or any portion thereof; (ii) technical failures of any kind, including but not limited to the malfunction of any computer, cable, network, hardware, or software, or other mechanical equipment; (iii) the unavailability or inaccessibility of any transmissions, telephone, or Internet service; (iv) unauthorized human intervention in any part of the entry process or the Promotion; (v) electronic or human error in the administration of the Promotion or the processing of entries.
            {"\n\n"}
            11. Disputes: THIS Campaign IS GOVERNED BY THE LAWS OF The United States of America AND Washington State, WITHOUT RESPECT TO CONFLICT OF LAW DOCTRINES. As a condition of participating in this Campaign, participant agrees that any and all disputes that cannot be resolved between the parties, and causes of action arising out of or connected with this Campaign, shall be resolved individually, without resort to any form of class action, exclusively before a court located in Washington having jurisdiction. Further, in any such dispute, under no circumstances shall participant be permitted to obtain awards for, and hereby waives all rights to, punitive, incidental, or consequential damages, including reasonable attorney’s fees, other than participant’s actual out-of-pocket expenses (i.e. costs associated with entering this Campaign). Participant further waives all rights to have damages multiplied or increased.
            {"\n\n"}
            12. Privacy Policy: Information submitted with an entry is subject to the Privacy Policy stated on the Olympia Top 10 website. 
            {"\n\n"}
            13. Winners List: To obtain a copy of the Winner’s name or a copy of these Official Rules, mail your request along with a stamped, self-addressed envelope to: Olympia Top 10. Requests must be received no later than August 30, 2021 at 12:00 PM PST.
            {"\n\n"}
            14. Sponsor: The Sponsor of the Campaign is Olympia Top 10.
            {"\n\n"}
            15. Facebook: The Campaign hosted by Olympia Top 10 is in no way sponsored, endorsed, administered by, or associated with Facebook.
            {"\n\n"}
            16. By checking the entry form, You, the Contestant, have affirmatively reviewed, accepted, and agreed to all of the Official Rules.
            </Text>
        </View>
    );

}

export default ContestRules;